### ISSUE TITLE
gzro windows wallet crash

### ISSUE THREAD

**Issue by emraan361** [GZR0/GRZ0#1]
hello im useing windows wallet suddunly its crash please solve it

**Comment by kkoenen** [comment]
The cause of any crash or freeze is highly dependent on the specifics of your system and its state just before the error. Think of OS, patch level, other software, etc. etc. You can restore your wallet by rebooting it. If that doesn't help, you can do a clean install and copy in the backup of your wallet.dat file (it's in %appdata%\gravity by default).

Without any extra information and a means to repeat the error, there is not much more we can do at this point.
